"""create migrations

Revision ID: e1541a9eb8d5
Revises: 
Create Date: 2018-07-31 14:37:24.727047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1541a9eb8d5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('config_name', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('hostname', sa.String(length=64), nullable=True),
    sa.Column('database', sa.String(length=64), nullable=True),
    sa.Column('port', sa.String(length=10), nullable=True),
    sa.Column('dialect', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('config_name')
    )
    op.create_table('report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_name', sa.String(length=64), nullable=True),
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.Column('hour', sa.Integer(), nullable=True),
    sa.Column('minute', sa.Integer(), nullable=True),
    sa.Column('day', sa.Integer(), nullable=True),
    sa.Column('query_text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['config_id'], ['configuration.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report')
    op.drop_table('configuration')
    # ### end Alembic commands ###
